# Generated by Django 5.2 on 2025-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_photoidentification'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='care_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='suggested_water_days',
            field=models.PositiveIntegerField(blank=True, help_text='Set by API suggestion', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
