# Generated by Django 5.2 on 2025-05-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_care_instructions_plant_soil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, default='plant_images/default.jpg', null=True, upload_to='plant_images/'),
        ),
    ]
