# Generated by Django 5.2 on 2025-05-06 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 6, 7, 3, 10, 694595, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
