# Generated by Django 5.2 on 2025-05-06 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_plant_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
