# Generated by Django 5.2 on 2025-05-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_plant_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='care_instructions',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='suggested_water_days',
        ),
        migrations.AddField(
            model_name='plant',
            name='common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='info_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='other_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistplant',
            name='common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wishlistplant',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='wishlistplant',
            name='info_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wishlistplant',
            name='other_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistplant',
            name='perenual_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistplant',
            name='sunlight',
            field=models.CharField(blank=True, choices=[('full_shade', 'Full Shade'), ('part_shade', 'Partial Shade'), ('sun-part_shade', 'Sun to Partial Shade'), ('full_sun', 'Full Sun')], max_length=20),
        ),
        migrations.AddField(
            model_name='wishlistplant',
            name='watering',
            field=models.CharField(blank=True, choices=[('frequent', 'Frequent'), ('average', 'Average'), ('minimum', 'Minimum'), ('none', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, choices=[('full_shade', 'Full Shade'), ('part_shade', 'Partial Shade'), ('sun-part_shade', 'Sun to Partial Shade'), ('full_sun', 'Full Sun')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering',
            field=models.CharField(blank=True, choices=[('frequent', 'Frequent'), ('average', 'Average'), ('minimum', 'Minimum'), ('none', 'None')], max_length=20),
        ),
    ]
