# Generated by Django 5.2.1 on 2025-05-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_remove_plant_care_instructions_remove_plant_soil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
